swipe:
  3:
    left:
      sendkey: "LEFTMETA+L"
    right:
      sendkey: "LEFTMETA+H"
    up:
      sendkey: "LEFTMETA+J"
    down:
      sendkey: "LEFTMETA+K"
  4:
    left:
      command: "bspc desktop -f next.local"
    right:
      command: "bspc desktop -f prev.local"
    up:
      command: "bspc desktop -f '^1'"
    down:
      command: "bspc desktop -f last"

interval:
  swipe: 0.75
