swipe:
  3:
    left:
      command: "bspc node -f prev.local.!hidden.window"
    right:
      command: "bspc node -f next.local.!hidden.window"
  4:
    left:
      command: "bspc desktop -f next.local"
    right:
      command: "bspc desktop -f prev.local"
    up:
      command: "bspc desktop -f '^1'"
    down:
      command: "bspc desktop -f last"

interval:
  swipe: 0.75
