swipe:
  3:
    left:
      command: "bspc node -f prev.local.!hidden.window"
    right:
      command: "bspc node -f next.local.!hidden.window"
    up:
      command: "hsetroot -fill ~/Pictures/Background/78172096.jpg &"
    down:
      command: "hsetroot -tile $(find ~/Pictures/limboPro.xyz -type f | shuf -n 1) &"
  4:
    left:
      command: "bspc desktop -f next.local"
    right:
      command: "bspc desktop -f prev.local"
    down:
      command: "bspc desktop -f last"

pinch:
  4: 
    in:
      command: ""
    out:
      command: ""

threshold:
  pinch: 0.5

interval:
  swipe: 0.75
  pinch: 0.5
