#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
picom &
feh --bg-fill --randomize ~/Pictures/Background/* &
$HOME/.config/polybar/launch.sh &
redshift &
dunst &
greenclip daemon &
fcitx5 &
clash &
aria2c --conf-path=/home/huizhi/.config/aria2/aria2.conf &
nutstore &
telegram-desktop &
netease-cloud-music-gtk &
mailspring &
virtualbox &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width           0
bspc config window_gap             10
bspc config focus_follows_pointer  true

bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc rule -a example desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a Netease-cloud-music-gtk desktop='^10'
bspc rule -a Mailspring desktop='^10'
bspc rule -a Org.gnome.clocks state=floating
bspc rule -a Gnome-calculator state=floating