#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill --randomize ~/Pictures/Background/* &
$HOME/.config/polybar/launch.sh &

nutstore &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width           0
bspc config window_gap             10

bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc rule -a example desktop='^8' state=floating follow=on
